/* tslint:disable */
/* eslint-disable */
/**
 * rust_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    email?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NewUser
     */
    employeeNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    gecos?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    loginId: string;
}

/**
 * Check if a given object implements the NewUser interface.
 */
export function instanceOfNewUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "loginId" in value;

    return isInstance;
}

export function NewUserFromJSON(json: any): NewUser {
    return NewUserFromJSONTyped(json, false);
}

export function NewUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'employeeNumber': !exists(json, 'employee_number') ? undefined : json['employee_number'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'gecos': !exists(json, 'gecos') ? undefined : json['gecos'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'loginId': json['login_id'],
    };
}

export function NewUserToJSON(value?: NewUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'employee_number': value.employeeNumber,
        'first_name': value.firstName,
        'gecos': value.gecos,
        'last_name': value.lastName,
        'login_id': value.loginId,
    };
}

